In [1]:
!pip3 install numpy

In [2]:
import numpy as np
import time

In [3]:
#execution performance
size = 1_000_000
st1 = time.time()
py_list = list(range(size))
sq_list = [x**2 for x in py_list]
en1 = time.time()
print(en1-st1)
st = time.time()
arr = np.array(py_list)
sq = arr**2
en = time.time()
print(en - st)


0.280590295791626
0.10698175430297852


In [4]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype)
arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype)
print(arr2.shape,arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
(6,) (5,)


In [5]:
list2d = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list2d)
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [15]:
#create 
arr12 = np.zeros((2,3),dtype="int64")
print(arr12,arr12.shape)
arr22 = np.ones((2,3),dtype = "int64")
print(arr22,arr22.shape)
arr44 = np.eye(4,4)
print(arr44,arr44.shape)
arr55 = np.full((3,4),100)
print(arr55,arr55.shape)
arr5 = np.arange(0,11,2)
print(arr5,arr5.shape)
arr6 = np.linspace(1,100,4)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [23]:
#properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [32]:
#operation
arr = np.array([[1,2,3],[4,5,6]])
print(arr.reshape(3,2))
print(arr[arr>2])
print(arr.flatten())
#slicing[start,end,step]
print(arr[1:4])
print(arr[1:])
print(arr[:2])

[[1 2]
 [3 4]
 [5 6]]
[3 4 5 6]
[1 2 3 4 5 6]
[[4 5 6]]
[[4 5 6]]
[[1 2 3]
 [4 5 6]]


In [37]:
#multidimentioanl array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(arr[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[[2]
 [5]]


In [42]:
#3d array
arr = np.array([[[1,2],[3,4],[5,6]],[[5,7],[8,9],[5,6]]])
print(arr)
print(arr[0,1,1]) #to acess 4 from matrix
#slicing
print(arr[:,0, :])

[[[1 2]
  [3 4]
  [5 6]]

 [[5 7]
  [8 9]
  [5 6]]]
4
[[1 2]
 [5 7]]


In [43]:
#vectorization
arr = np.array([1,2,3,4,4,5])
print(arr**3) #treat as one 
#broadcasting
print(arr+5) #stretch 5 to make it suitable to add with arr

[  1   8  27  64  64 125]
[ 6  7  8  9  9 10]


In [48]:
#math function
arr = np.array([1,2,3.3,4,5])

#aggrigation
print(np.sum(arr))
print(np.var(arr))# varience
#power
print(np.pow(arr,3))
#log 
print(np.log(arr))
print(np.log2(arr))
#round
print(np.round(arr))

15.3
2.0144
[  1.      8.     35.937  64.    125.   ]
[0.         0.69314718 1.19392247 1.38629436 1.60943791]
[0.         1.         1.72246602 2.         2.32192809]
[1. 2. 3. 4. 5.]
